package com.timo.timoterminal.enums

enum class SharedPreferenceKeys {
    TIMO_TERMINAL_ID,
    DEVICE_UUID,
    SERVER_URL,
    COMPANY,
    USER,
    PASSWORD,
    TOKEN,
    LANGUAGE,
    TIMEZONE,
    UI_VISIBLE,
    SOUND_ACTIVITY,
    BOOKING_MESSAGE_TIMEOUT_IN_SEC,
    HAS_UPDATE,
    UPDATE_VERSION,
    LAST_VERSION,
    LAST_DATE,
    DARK_MODE_ENABLED
}

enum class ProjectPreferenceKeys {// Always start with PROJECT_ to avoid conflicts with other keys
    PROJECT_ACTIVITY_TYPE,
    PROJECT_ACTIVITY_TYPE_MATRIX,
    PROJECT_BILLABLE,
    PROJECT_CUSTOMER,
    PROJECT_DESCRIPTION,
    PROJECT_DRIVEN_KM,
    PROJECT_ENTRY_TYPE,
    PROJECT_EVALUATION,
    PROJECT_JOURNEY,
    PROJECT_KM_FLAT_RATE,
    PROJECT_ORDER_NO,
    PROJECT_PERFORMANCE_LOCATION,
    PROJECT_PREMIUNMABLE,
    PROJECT_SKILL_LEVEL,
    PROJECT_TEAM,
    PROJECT_TICKET,
    PROJECT_TRAVEL_TIME,
    PROJECT_UNIT
}