package com.timo.timoterminal.enums

enum class TerminalCommands {
    COMMAND_UPDATE_ALL_USER,
    COMMAND_UPDATE_USER,
    COMMAND_DELETE_USER,
    COMMAND_DELETE_FP,
    COMMAND_ENROLL_CARD,
    COMMAND_ENROLL_FINGER,
    COMMAND_LOAD_PERMISSION,
    COMMAND_LOAD_LANGUAGE,
    COMMAND_REBOOT_TERMINAL,
    COMMAND_CHANGE_LANGUAGE,
    COMMAND_UPDATE_URL,
    COMMAND_UPDATE_APK
}